### PR TITLE
NSync sets config for container networking

### PR DESCRIPTION
**Pull request by dbellotti**
cc:@rosenhouse, @evanfarrar @emalm

### CODE REVIEW

**Comment by evanfarrar** [comment]
@SocalNick @utako,

@rosenhouse or I can speak to what we're doing overall here, as it spans a few other repos, but we're working on getting a application ID to our networking driver in order to associate apps to endpoints for name resolution.

**Comment by rosenhouse** [comment]
Yep.  https://github.com/cloudfoundry-incubator/diego-release/commit/82e176ceb9d1f765589f8f28fccfcd0d14b331aa added these new fields to the DesiredLRP and Tasks.  This change is necessary to set the values in those fields.

There will need to be a small change to diego-release to wire in a spec to the command line flag, e.g. https://github.com/sykesm/diego-release/commit/10d2e12cf88bb1a69a1c7b75d71d268d25a251cf

Happy to cross-team pair on this too.

**Comment by emalm** [comment]
Thanks, @evanfarrar. @jfmyers9, @SocalNick, and I looked over the proposed changes, and we have a few questions and concerns:
- What is the `ducati.network-id` network property supposed to signify? Is it right for that value to come through BOSH configuration (or is that temporary to give you exploratory room)? What happens to the container networking if an operator changes that value in the manifest and re-deploys, given that the DesiredLRPs are immutable?
- The LRP generation functions get the `app-guid` property from the `LogGuid` field on the desire-app request, presumably because that's the only place on that request where the app guid itself is present. But that seems coincidental. Would it make more sense for the desire-app request itself to change, either to add a NetworkGuid that is also the app guid or to add the app guid itself as an explicit field? (Of course, LogGuid would have to stick around for some time for backwards compatibility.)
- The CC-Bridge jobs are in the process of moving from diego-release to capi-release, so any BOSH-release changes should be made there as well. Really, we're to remove them from diego-release now, but we're waiting to cut CF v235 with all the Golang cleanup to prevent any pipeline interference and to ensure a slightly longer period of compatible CF/Diego releases.

Thanks,
Eric

**Comment by rosenhouse** [comment]
@ematpl @jfmyers9 @SocalNick @utako  We've updated this PR to reflect the plan we agreed to in our meeting earlier.  It now only sets the app-guid, using the coincidence of logguid = app-guid.  It no longer requires any changes to either BOSH release.

As discussed, whenever CAPI is ready, we're happy to cross-team pair on adding app-guid (or "network app id" or whatever we want to call it) to the desired app request coming from CC, and then update nsync to use that field on the request instead of relying on this coincidence.

Thanks!

-@rosenhouse & @jaydunk

**Comment by emalm** [comment]
Thanks, @rosenhouse! Pulling over to the Diego backlog to merge in.

Best,
Eric

**Pull request closed without merging**
